# SITEURL = 'https://blog.coracle.social'
SITENAME = 'Coracle'
SITESUBTITLE = 'A Dev Blog'
PROFILE_IMAGE = 'logo-square.png'
COLOR_THEME = 'dark'
GITHUB_URL = 'https://github.com/staab/coracle'
TIMEZONE = 'US/Pacific'
THEME = './pelican-themes/hyde'
